services:

    cqrs.handler.collection:
        class: Nixilla\CqrsBundle\Services\HandlerCollection

    cqrs.listener.collection:
        class: Nixilla\CqrsBundle\Services\ListenerCollection

    cqrs.projector.collection:
        class: Nixilla\CqrsBundle\Services\ProjectorCollection

    cqrs.handler.resolver:
        class: Nixilla\CqrsBundle\Services\HandlerResolver
        arguments: [ "@service_container", "@cqrs.serializer.camelTo_snake" ]

    cqrs.listener.resolver:
        class: Nixilla\CqrsBundle\Services\ListenerResolver
        arguments: [ "@cqrs.listener.collection" ]

    cqrs.projector.resolver:
        class: Nixilla\CqrsBundle\Services\ProjectorResolver
        arguments: [ "@cqrs.projector.collection" ]

    cqrs.serializer.camelTo_snake:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter